Introduce lib_driver_cmd_qcwcn as cc_defaults
error: external/wpa_supplicant_8/hostapd/Android.bp:713:1: "hostapd" depends on undefined module "lib_driver_cmd_qcwcn"
Co-Authored-By: Jyotiraditya Panda <jyotiraditya@aospa.co>